spring:
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: false
    clean-on-validation-error: true
    baseline-on-migrate: false
    clean-disabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
        connection:
          provider_disables_autocommit: false
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 128
          fetch_size: 128
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        cache:
          use_minimal_puts: true
          use_second_level_cache: false
  datasource:
    hikari:
      maximum-pool-size: 12
      minimum-idle: 6
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26257/spring_boot?sslmode=disable
#    url: jdbc:postgresql://192.168.1.99:26257/spring_boot?sslmode=disable
    username: root
    password:
#############################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
