########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  profiles:
    active: verbose,cloud
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    deserialization:
      fail_on_unknown_properties: false
      fail_on_ignored_properties: false
    default-property-inclusion: non_null
    locale: en_US
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

  datasource:
    url: jdbc:postgresql://localhost:26257/spring_boot_demo?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 15000
      validation-timeout: 5000
      maximum-pool-size: 25
      minimum-idle: 25
      register-mbeans: false

  flyway:
    connect-retries: 10
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true
    baseline-on-migrate: true
    clean-disabled: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
        connection:
          provider_disables_autocommit: false
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 128
          fetch_size: 128
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        cache:
          use_minimal_puts: true
          use_second_level_cache: false

server:
  port: 8090
  gzip:
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    include-message: always
