spring:
  datasource:
    url: jdbc:cockroachdb://192.168.1.99:26257/spring_boot_demo?sslmode=disable&implicitSelectForUpdate=true&retryTransientErrors=true
#    url: jdbc:cockroachdb://192.168.1.99:26257/spring_boot_demo?sslmode=disable&retryTransientErrors=true
#    url: jdbc:cockroachdb://192.168.1.99:26257/spring_boot_demo?sslmode=disable&implicitSelectForUpdate=true
    username: root
    password:
    driver-class-name: io.cockroachdb.jdbc.CockroachDriver
