spring:
  datasource:
    url: jdbc:cockroachdb://localhost:26257/spring_boot_demo?sslmode=disable&implicitSelectForUpdate=true&retryTransientErrors=true
    username: root
    password:
    driver-class-name: io.cockroachdb.jdbc.CockroachDriver
